apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-secretsk8s
spec:
  provider: azure
  secretObjects:
  - data:
    - key: mongodburi
      objectName: "mongodburi"
    secretName: mongodburi
    type: Opaque
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"   
    userAssignedIdentityID: "d70362cc-1119-4875-bf2f-01a2875d4443"
    keyvaultName: secretsk8s
    objects:  |
      array:
        - |
          objectName: mongodburi
          objectType: secret
    tenantId: "cb45bd65-7a9f-4e71-9f91-614c10c9cbf4"